### ISSUE TITLE
Create Project Milestones

### ISSUE THREAD

**Issue by wpank** [sourcecred/sourcecred#1071]
Milestones help track the progress of associated groups of issues and pull requests. Milestones provide a clear sense of direction of where projects are going in accordance with their priorities. 

Additionally, Milestones help in prioritizing which issues/pull requests within an appropriate group are most important. 

[See Github's page on Milestones for further information](https://help.github.com/articles/about-milestones/)

In accordance with the current 2019 OKRs, potential Milestones could be:
- [ ] Use temporal data in cred analysis
- [ ] Add support for Heuristics
- [ ] Add pass through semantics
- [ ] Add identity resolution
- [ ] Add cred decomposition
- [ ] Add file-level cred analysis
- [ ] Add function call graph cred analysis
- [ ] Enable communities to manually add nodes to the graph
- [ ] Make external documentation
- [ ] Reach x amount of contributors

**Comment by decentralion** [comment]
I think this would be really helpful for the project. Going to cc @asood123 who has talked about potentially helping SourceCred with project management.
