### ISSUE TITLE
Make SourceCred robust on large repositories

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1256]
Right now, there are a lot of issues with downloading large GitHub repositories that conspire to make SourceCred brittle on large repos. #1023 is an example of this.

Here are the sub-issues I'm aware of
- [ ] Not robust to GitHub entities that have changed their typename (#998)
- [ ] Not robust to GitHub node deletion (#938)
- [ ] We need to handle the known contract violation errors in the api ([#996])

This issue will track progress towards the overall goal of making SC robust and reliable on large repos, like TensorFlow.

**Comment by Beanow** [comment]
Perhaps useful to document problematic repos for testing, I ran into more but let me update this as I bump into them.

Error: Cannot update data for nonexistent node: undefined
- passbolt/passbolt_api

**Comment by decentralion** [comment]
@Beanow one of the ways this issue comes up is if a node was deleted. Possibly during the update itself, but most likely between when you created your cache and your latest update. (See #938). So if you haven't already, I recommend clearing your cache and trying again.

The very least we can do is try to get better error messages on all of these issues, so we at least know why the update failed, give a hint as to whether a cache clear may fix it, and link to the right issue on GitHub.

@wchargin would you be willing to take on just updating the error messages so they point to the right failure cause?

**Comment by Beanow** [comment]
I believe it wasn't the cache. Try running from a container with a fresh data folder:

```sh
time SOURCECRED_GITHUB_TOKEN="xxxxxx" \
  docker run -ti --rm --env SOURCECRED_GITHUB_TOKEN \
  -p 8080:8080 sourcecred/sourcecred dev-preview quasarframework/quasar-cli
```

<pre><span style="background-color:#3465A4"><font color="#EEEEEC"><b>  GO  </b></font></span> load-quasarframework/quasar-cli
<span style="background-color:#3465A4"><font color="#EEEEEC"><b>  GO  </b></font></span> github/quasarframework/quasar-cli
Error: Cannot update data for nonexistent node: undefined
    at Mirror._nontransactionallyUpdateOwnData (webpack:///./src/graphql/mirror.js?:412:161)
    at Mirror._nontransactionallyUpdateData (webpack:///./src/graphql/mirror.js?:239:235)
    at eval (webpack:///./src/graphql/mirror.js?:244:638)
    at _inTransaction (webpack:///./src/graphql/mirror.js?:560:142)
    at Mirror._updateStep (webpack:///./src/graphql/mirror.js?:244:555)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Mirror.update (webpack:///./src/graphql/mirror.js?:274:44)
    at async fetchGithubRepo (webpack:///./src/plugins/github/fetchGithubRepo.js?:39:74)
    at async loadGraph (webpack:///./src/plugins/github/loadGraph.js?:17:213)
    at async load (webpack:///./src/api/load.js?:26:92)

real	0m37,744s
user	0m0,017s
sys	0m0,012s
</pre>

**Comment by wchargin** [comment]
Thanks for the repro. It’s another unfaithful query result. An issue has
a reaction from an organization, which GitHub is telling us is a user:

  - <https://github.com/quasarframework/quasar-cli/issues/164>
  - <https://github.com/airgram>

I’ll patch this organization out manually for now, but I have an idea
for an easy patch that will at least detect these issues in the future.

**Comment by wchargin** [comment]
> I’ll patch this organization out manually for now

See #1335.

> but I have an idea for an easy patch that will at least detect these
> issues in the future.

See #1336.
