### ISSUE TITLE
Remove deprecated load functionality

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1629]
Meta issue to track and discuss what still needs to be removed from the load system, now that it has been refactored.

- [x] Remove previous `api/load` implementation #1630.
- [x] Remove deprecated plugin load entrypoints. #1634 / #1635
- [x] Remove (githubToken: string) signatures from load system refactor #1626 / #1636.

**Comment by Beanow** [comment]
Believe no particular deprecated components are left.
