### ISSUE TITLE
About: Discord Plugin

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1721]
# Summary

We're developing a new plugin for [Discord](https://sourcecred.io/discord-invite).

Discord is one of the media the SourceCred community uses. Because it offers synchronous chat channels and voice, it fits a different role than the currently supported Discourse and GitHub platforms. Adding Discord data to the graph would allow new ways of attributing, such as `#didathing` and `#props`, or ![:sourcecred:](https://raw.githubusercontent.com/sourcecred/sourcecred/master/src/assets/logo/rasterized/logo_16.png) emoji reactions.

# Status:

A proof-of-concept and prototype has been developed at the CredCon hackathon.
@BrianLitwin is currently working to turn this into production-ready code.

# Champion<sup>[?](https://discourse.sourcecred.io/t/about-champions-and-heroes/291)</sup>

@BrianLitwin

# Implementation plan

- [x] Explore API documentation and requirements. (#1651)
- [x] Build a prototype. (https://github.com/sourcecred/sourcecred/tree/discord)
- [ ] Refine prototype to production-ready code.
- [ ] Document and package for release.
