### ISSUE TITLE
About: GitHub Action

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1727]
# Summary

Creating a GitHub Action, which automates updating a SourceCred instance.

As touched on in [Productivity / Quality of Life for instance maintainers](https://discourse.sourcecred.io/t/productivity-quality-of-life-for-instance-maintainers/651), there’s a clear need to automate maintenance tasks surrounding a SourceCred instance.

This GitHub action will provide an easy to adopt, reproducible way to keep SourceCred instances up to date. By way of wrapping SourceCred in a container with variables exposed via the GitHub actions interface (action.yml) we can easily update the internals without changing the UI.

# Status

A working action is created at https://github.com/vsoch/cred-action

Some improvements and reviews are being worked on before release.
It also needs to be moved and renamed to the SourceCred GitHub organization.

# Champion<sup>[?](https://discourse.sourcecred.io/t/about-champions-and-heroes/291)</sup>

@vsoch

# Implementation plan

- [x] Create initial prototype: https://github.com/vsoch/cred-action
- [ ] Address open improvements: https://github.com/vsoch/cred-action/issues
- [ ] Rename and move to SourceCred GitHub organization.
- [ ] Create versioned release.

# Related

- [Initiative on the forums](https://discourse.sourcecred.io/t/the-sourcecred-github-action/683)

**Comment by vsoch** [comment]
We are waiting on @wchargin for making progress here.
