### ISSUE TITLE
About: Boosting

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1729]
# Summary

Creating a Boosting feature in SoucreCred.

> Boosting is a mechanism that allows people in the community to express that they believe a contribution is undervalued; that is to say, that a contribution is receiving too little Cred. In order to boost something, the booster must have Grain. They can then “plant” the Grain in order to Boost the contribution. That causes the Cred of the contribution to increase, in proportion to the amount of Grain that was planted.

@burrrata summarized [in this topic](https://discourse.sourcecred.io/t/boosting-a-prediction-market-on-ideas/306).

# Status

Much discussion and exploration of the Boosting concept has taken place. Such as on the forums and during CredCon. For the technical implementation there are still some dependencies blocking it.

# Team

# Implementation plan

- [ ] Have "native" support for Grain built into SourceCred. (in-progress)
- [ ] Write a design doc, to outline how the first version of Boosting will be implemented. It should be reviewed from both a technical and cryptoeconomic angle. **Important**, it's highly recommended to do this before working on implementations.
- [ ] TBD: further planning depends on the design doc.

# Related

**Comment by Beanow** [comment]
cc @decentralion I think you have more context to see if this description and plan are accurate :]

**Comment by decentralion** [comment]
Having a design doc first makes sense to me. I'll be the logical candidate to write such a doc, once I've done the grain ledger stuff.
