### ISSUE TITLE
About: Grain ledger

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1730]
# Summary

Creating a Grain ledger for SoucreCred.

> Grain (a project-specific token tied to cred) is a vital part of the SourceCred system. However, right now we don’t have any code-reviewed infrastructure for distributing, tracking, or displaying grain balances. Instead, grain is distributed based on non-code-reviewed Observable notebooks (see [payouts](https://discourse.sourcecred.io/t/sourcecred-contributor-payouts/298)), recorded in undocumented file formats via a manual process, and then displayed through notebooks.
>
> This system is highly manual, non-robust, and not a good fit for other projects which are adopting SourceCred. We need to build proper infrastructure for distributing, tracking, and displaying Grain.

Summary by @decentralion from [initiative topic](https://discourse.sourcecred.io/t/grain-ledger/657)

# Status

# Team

- @decentralion 

# Implementation plan

- [ ] Write the ledger module
- [ ] Write the distribution module
- [ ] Write the legacy import module
- [ ] Write the display module
- [ ] Code review, testing
- [ ] Integrate with SourceCred CLI and automation

# Related

- [Initiative on forums](https://discourse.sourcecred.io/t/grain-ledger/657)

**Comment by Beanow** [comment]
@decentralion @hammadj grave digging in the forums here: https://discourse.sourcecred.io/t/credsperiment-week-1-payouts/227/3

How do you feel about signing the ledger?

**Comment by hammadj** [comment]
> @decentralion @hammadj grave digging in the forums here: https://discourse.sourcecred.io/t/credsperiment-week-1-payouts/227/3
> 
> 
> 
> How do you feel about signing the ledger?

I think it’s a great idea. For MetaGame we will likely use Aragon Agent to sign things “as the DAO”, but for now it could just be a PGP signature from @decentralion’s Keybase

**Comment by decentralion** [comment]
Hmm, how would this work in practice? I want the cred/grain distribution to be able to happen automatically via a GitHub action. In which case, the signing keys would need to be included in our automated deploy infra. That would be owned by sourcecred maintainers, so it wouldn't make sense for me to upload my personal signing key. We would have a sourcecred team signing key.

Which could definitely make sense, and be reasonable so that third parties can inspect the data (w.o. access to GitHub) and verify that they have the real ledger, assuming they kept the SC team key.

However, would we need to put this in the ledger? Wouldn't it suffice to just sign the hash of the ledger? Doesnt seem like it needs to be a first class feature.

In either case, it feels like complexity that we don't need for beta-1, so I suggest we punt on it for now either way.
