### ISSUE TITLE
About: Set up versioned release process

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1779]
## Summary

This is an [Initiative](https://sourcecred.io/docs/concepts/initiatives) to create a repeatable workflow for versioned releases.

These releases are helpful synchronization points. They're not really aimed at developers, but rather the rest of the ecosystem. Because releases can sync with:
- A blog post about what's new.
- Ensuring documentation and guides exist for the changes made.
- A well supported upgrade from the version you're using to the new one.

Though there is some benefit to developers as well. Because fewer versions of the code need to be supported, it reduces some overhead.

Because we're moving from [alpha into beta](https://github.com/sourcecred/docs/issues/68), we'll want to increase support for the ecosystem at large. So a regular release cadence becomes more important as well.

## Status

Experimenting with workflows has started as part of this tracking issue #1679.

## Team

- @Beanow

## Implementation plan

- [ ] Experiment with release workflows during alpha.
  _Serves to find pain points and test syncing with other processes._
- [ ] Distill a workflow & template from experiments.
- [ ] Raise expectations in workflow steps from experimental to beta quality.
  _For example how good the docs should be, how well tested a release should be, etc._
